name: Build Release

permissions:
  contents: write  # 需要写权限来提交文件到 repo

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'caddy version to build (use "latest" for the latest release)'
        required: false
        default: "latest"
  schedule:
    - cron: "0 * * * *"

jobs:
  check_caddy_release:
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.compare_release.outputs.new_release }}
      caddy_version: ${{ steps.get_latest_release.outputs.caddy_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史，以便后续提交

      - name: Get latest Caddy release
        id: get_latest_release
        run: |
          CADDY_VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)
          echo "Latest Caddy version: $CADDY_VERSION"
          echo "caddy_version=$CADDY_VERSION" >> $GITHUB_OUTPUT

      - name: Compare with previous release
        id: compare_release
        run: |
          if [ -f "caddy-version.txt" ]; then
            PREVIOUS_VERSION=$(cat caddy-version.txt)
          else
            PREVIOUS_VERSION="NONE"
          fi
          echo "Previous version: $PREVIOUS_VERSION"
          echo "Current version: ${{ steps.get_latest_release.outputs.caddy_version }}"
          if [ "${{ steps.get_latest_release.outputs.caddy_version }}" != "$PREVIOUS_VERSION" ]; then
            echo "New Caddy release detected!"
            echo "new_release=true" >> $GITHUB_OUTPUT
          else
            echo "No new release."
            echo "new_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Update version file in repo
        if: steps.compare_release.outputs.new_release == 'true'
        run: |
          echo "${{ steps.get_latest_release.outputs.caddy_version }}" > caddy-version.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add caddy-version.txt
          git commit -m "Update caddy version to ${{ steps.get_latest_release.outputs.caddy_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: check_caddy_release
    if: needs.check_caddy_release.outputs.new_release == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, amd64v3, arm64, arm64v9]
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Determine caddy Version
        id: get_version
        run: |
          LATEST_VERSION="${{ needs.check_caddy_release.outputs.caddy_version }}"
          echo "caddy version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Install xcaddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build Custom caddy Binary
        run: |
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            xcaddy build ${{ steps.get_version.outputs.version }} \
              --with github.com/mholt/caddy-l4@latest \
              --output caddy_${{ matrix.arch }}
          elif [ "${{ matrix.arch }}" = "amd64v3" ]; then
            GOAMD64=v3 xcaddy build ${{ steps.get_version.outputs.version }} \
              --with github.com/mholt/caddy-l4@latest \
              --output caddy_${{ matrix.arch }}
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            GOARCH=arm64 xcaddy build ${{ steps.get_version.outputs.version }} \
              --with github.com/mholt/caddy-l4@latest \
              --output caddy_${{ matrix.arch }}
          elif [ "${{ matrix.arch }}" = "arm64v9" ]; then
            CGO_ENABLED=1 GOARCH=arm64 xcaddy build ${{ steps.get_version.outputs.version }} \
              --with github.com/mholt/caddy-l4@latest \
              --output caddy_${{ matrix.arch }} \
              -ldflags "-extldflags '-march=armv9-a'"
          else
            echo "Unsupported architecture"
            exit 1
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: caddy-${{ matrix.arch }}
          path: |
            caddy_${{ matrix.arch }}
            caddy_${{ matrix.arch }}v3
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ format('{0}-{1}', needs.build.outputs.version, github.run_id) }}
          name: "${{ needs.build.outputs.version }} (Build ${{ github.run_id }})"
          body: "Weekly Build triggered by Caddy release ${{ needs.build.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ format('{0}-{1}', needs.build.outputs.version, github.run_id) }}
          files: |
            artifacts/caddy-amd64/caddy_amd64
            artifacts/caddy-amd64/caddy_amd64v3
            artifacts/caddy-arm64/caddy_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
