name: Build Custom Caddy with Layer4

on:
  # 手动触发，并允许传入要构建的版本（默认 latest）
  workflow_dispatch:
    inputs:
      version:
        description:
          'Caddy version to build (use "latest" for the latest release)'
        required: false
        default: "latest"
  # 每小时定时检测新版发布
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 开启 go module 支持
      GO111MODULE: "on"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Determine Caddy Version
        id: get_version
        run: |
          if [ "${{ github.event.inputs.version }}" = "latest" ]; then
            LATEST_VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)
          else
            LATEST_VERSION="${{ github.event.inputs.version }}"
          fi
          echo "Caddy version: $LATEST_VERSION"
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Install xcaddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          # 将 $HOME/go/bin 添加到 PATH 中，确保 xcaddy 可用
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build Custom Caddy Binary
        run: |
          xcaddy build $LATEST_VERSION --with github.com/mholt/caddy-l4

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: caddy
          path: ./caddy

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: caddy
          path: .
  
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_VERSION }}
          name: "Caddy ${LATEST_VERSION}"
          body: "Custom build of Caddy with layer4 module."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_VERSION }}
          files: ./caddy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
